// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdcfswrkiunqvyexefcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkY2Zzd3JraXVucXZ5ZXhlZmNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MDY3NjMsImV4cCI6MjA2NTM4Mjc2M30.sMgr7PmECsIZHWSCzy11sNGv-tqfgAl4kPHRTTFP9TQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);